version: "3.10"
services:
  zookeeper: # default port 2181
    image: wurstmeister/zookeeper:3.4.6
  kafka: # default port 9092
    image: wurstmeister/kafka:2.12-2.3.0
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "default:2:1" # Topic명:Partition개수:Replica개수
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  redis:
    image: redis:6.2.6
  posts: &posts
    restart: always
    depends_on:
      - zookeeper
      - kafka
    build: services/posts
    volumes:
      - ./services/posts:/home/posts/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
  posts_consumer:
    <<: *posts
    command: >
      sh -c "python consumer.py"
  client:
    restart: always
    depends_on:
      - posts
    build: services/client
    volumes:
      - ./services/client:/app
  nginx:
    depends_on:
      - client
      - posts
    restart: always
    build:
      context: ./nginx
    ports:
      - "3050:80"
